// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $AddToCartButton_linx from "./islands/AddToCartButton/linx.tsx";
import * as $AddToCartButton_nuvemshop from "./islands/AddToCartButton/nuvemshop.tsx";
import * as $AddToCartButton_shopify from "./islands/AddToCartButton/shopify.tsx";
import * as $AddToCartButton_vnda from "./islands/AddToCartButton/vnda.tsx";
import * as $AddToCartButton_vtex from "./islands/AddToCartButton/vtex.tsx";
import * as $AddToCartButton_wake from "./islands/AddToCartButton/wake.tsx";
import * as $BannerPointOfSale from "./islands/BannerPointOfSale.tsx";
import * as $BuyButtoCustom from "./islands/BuyButtoCustom.tsx";
import * as $Canonical from "./islands/Canonical.tsx";
import * as $Clock from "./islands/Clock.tsx";
import * as $Exploring from "./islands/Exploring.tsx";
import * as $Form from "./islands/Form.tsx";
import * as $Header_Alert from "./islands/Header/Alert.tsx";
import * as $Header_Buttons from "./islands/Header/Buttons.tsx";
import * as $Header_Cart_linx from "./islands/Header/Cart/linx.tsx";
import * as $Header_Cart_nuvemshop from "./islands/Header/Cart/nuvemshop.tsx";
import * as $Header_Cart_shopify from "./islands/Header/Cart/shopify.tsx";
import * as $Header_Cart_vnda from "./islands/Header/Cart/vnda.tsx";
import * as $Header_Cart_vtex from "./islands/Header/Cart/vtex.tsx";
import * as $Header_Cart_wake from "./islands/Header/Cart/wake.tsx";
import * as $Header_Drawers from "./islands/Header/Drawers.tsx";
import * as $Header_Searchbar from "./islands/Header/Searchbar.tsx";
import * as $IndexRolex from "./islands/IndexRolex.tsx";
import * as $Installments from "./islands/Installments.tsx";
import * as $MenuRolex from "./islands/MenuRolex.tsx";
import * as $Newsletter from "./islands/Newsletter.tsx";
import * as $NewsletterDefaul from "./islands/NewsletterDefaul.tsx";
import * as $OutOfStock from "./islands/OutOfStock.tsx";
import * as $PaginationCustom from "./islands/PaginationCustom.tsx";
import * as $ProductImageZoom from "./islands/ProductImageZoom.tsx";
import * as $ProductMainRolex from "./islands/ProductMainRolex.tsx";
import * as $SearchControls from "./islands/SearchControls.tsx";
import * as $SeloRolex from "./islands/SeloRolex.tsx";
import * as $SeloTudor from "./islands/SeloTudor.tsx";
import * as $ShippingSimulation from "./islands/ShippingSimulation.tsx";
import * as $ShowMore from "./islands/ShowMore.tsx";
import * as $TagCanonical from "./islands/TagCanonical.tsx";
import * as $TagKeyWord from "./islands/TagKeyWord.tsx";
import * as $UserLogged from "./islands/UserLogged.tsx";
import * as $WhatsFixed from "./islands/WhatsFixed.tsx";
import * as $WishlistButton_vtex from "./islands/WishlistButton/vtex.tsx";
import * as $WishlistButton_wake from "./islands/WishlistButton/wake.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/AddToCartButton/linx.tsx": $AddToCartButton_linx,
    "./islands/AddToCartButton/nuvemshop.tsx": $AddToCartButton_nuvemshop,
    "./islands/AddToCartButton/shopify.tsx": $AddToCartButton_shopify,
    "./islands/AddToCartButton/vnda.tsx": $AddToCartButton_vnda,
    "./islands/AddToCartButton/vtex.tsx": $AddToCartButton_vtex,
    "./islands/AddToCartButton/wake.tsx": $AddToCartButton_wake,
    "./islands/BannerPointOfSale.tsx": $BannerPointOfSale,
    "./islands/BuyButtoCustom.tsx": $BuyButtoCustom,
    "./islands/Canonical.tsx": $Canonical,
    "./islands/Clock.tsx": $Clock,
    "./islands/Exploring.tsx": $Exploring,
    "./islands/Form.tsx": $Form,
    "./islands/Header/Alert.tsx": $Header_Alert,
    "./islands/Header/Buttons.tsx": $Header_Buttons,
    "./islands/Header/Cart/linx.tsx": $Header_Cart_linx,
    "./islands/Header/Cart/nuvemshop.tsx": $Header_Cart_nuvemshop,
    "./islands/Header/Cart/shopify.tsx": $Header_Cart_shopify,
    "./islands/Header/Cart/vnda.tsx": $Header_Cart_vnda,
    "./islands/Header/Cart/vtex.tsx": $Header_Cart_vtex,
    "./islands/Header/Cart/wake.tsx": $Header_Cart_wake,
    "./islands/Header/Drawers.tsx": $Header_Drawers,
    "./islands/Header/Searchbar.tsx": $Header_Searchbar,
    "./islands/IndexRolex.tsx": $IndexRolex,
    "./islands/Installments.tsx": $Installments,
    "./islands/MenuRolex.tsx": $MenuRolex,
    "./islands/Newsletter.tsx": $Newsletter,
    "./islands/NewsletterDefaul.tsx": $NewsletterDefaul,
    "./islands/OutOfStock.tsx": $OutOfStock,
    "./islands/PaginationCustom.tsx": $PaginationCustom,
    "./islands/ProductImageZoom.tsx": $ProductImageZoom,
    "./islands/ProductMainRolex.tsx": $ProductMainRolex,
    "./islands/SearchControls.tsx": $SearchControls,
    "./islands/SeloRolex.tsx": $SeloRolex,
    "./islands/SeloTudor.tsx": $SeloTudor,
    "./islands/ShippingSimulation.tsx": $ShippingSimulation,
    "./islands/ShowMore.tsx": $ShowMore,
    "./islands/TagCanonical.tsx": $TagCanonical,
    "./islands/TagKeyWord.tsx": $TagKeyWord,
    "./islands/UserLogged.tsx": $UserLogged,
    "./islands/WhatsFixed.tsx": $WhatsFixed,
    "./islands/WishlistButton/vtex.tsx": $WishlistButton_vtex,
    "./islands/WishlistButton/wake.tsx": $WishlistButton_wake,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
