// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/ai-assistants.ts";
import * as $$$$$$$$$$$1 from "./apps/deco/algolia.ts";
import * as $$$$$$$$$$$2 from "./apps/deco/analytics.ts";
import * as $$$$$$$$$$$3 from "./apps/deco/brand-assistant.ts";
import * as $$$$$$$$$$$4 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$5 from "./apps/deco/implementation.ts";
import * as $$$$$$$$$$$6 from "./apps/deco/vtex.ts";
import * as $$$$$$$$$$$7 from "./apps/deco/weather.ts";
import * as $$$$$$$$$$$8 from "./apps/deco/workflows.ts";
import * as $$$$$$$$$$$9 from "./apps/decohub.ts";
import * as $$$$$$$$$$$10 from "./apps/site.ts";
import * as $$$2 from "./loaders/availableIcons.ts";
import * as $$$3 from "./loaders/icons.ts";
import * as $$$0 from "./loaders/Layouts/ProductCard.tsx";
import * as $$$1 from "./loaders/List/Sections.tsx";
import * as $$$$$$0 from "./sections/Animation/Animation.tsx";
import * as $$$$$$1 from "./sections/Bvlgari/Bvlgari.tsx";
import * as $$$$$$2 from "./sections/Cards/IconCardsCarousel.tsx";
import * as $$$$$$3 from "./sections/Cards/IconCardsCarouselWithImage.tsx";
import * as $$$$$$4 from "./sections/Cards/ImageCardsCarousel.tsx";
import * as $$$$$$5 from "./sections/Cards/ImageCardsCarouselWithImage.tsx";
import * as $$$$$$6 from "./sections/Cartier/Cartier.tsx";
import * as $$$$$$7 from "./sections/Category/CategoryBanner.tsx";
import * as $$$$$$8 from "./sections/Category/CategoryGrid.tsx";
import * as $$$$$$9 from "./sections/Category/CategoryList.tsx";
import * as $$$$$$10 from "./sections/Category/CategoryText.tsx";
import * as $$$$$$11 from "./sections/CollectionHub.tsx";
import * as $$$$$$12 from "./sections/Content/Benefits.tsx";
import * as $$$$$$13 from "./sections/Content/BlogPosts.tsx";
import * as $$$$$$14 from "./sections/Content/CallToAction.tsx";
import * as $$$$$$15 from "./sections/Content/Faq.tsx";
import * as $$$$$$16 from "./sections/Content/Features.tsx";
import * as $$$$$$17 from "./sections/Content/Hero.tsx";
import * as $$$$$$18 from "./sections/Content/ImageSection.tsx";
import * as $$$$$$19 from "./sections/Content/Intro.tsx";
import * as $$$$$$20 from "./sections/Content/Logos.tsx";
import * as $$$$$$21 from "./sections/Content/Partners.tsx";
import * as $$$$$$22 from "./sections/Content/RichText.tsx";
import * as $$$$$$23 from "./sections/Content/Table.tsx";
import * as $$$$$$24 from "./sections/Content/Testimonials.tsx";
import * as $$$$$$25 from "./sections/Content/TextWithImage.tsx";
import * as $$$$$$26 from "./sections/CookieDryzun.tsx";
import * as $$$$$$27 from "./sections/Dryzun/AboutDryzun.tsx";
import * as $$$$$$28 from "./sections/Dryzun/AboutInstitucional.tsx";
import * as $$$$$$29 from "./sections/Dryzun/BannerGrid.tsx";
import * as $$$$$$30 from "./sections/Dryzun/BannerList.tsx";
import * as $$$$$$31 from "./sections/Dryzun/BannerSingle.tsx";
import * as $$$$$$32 from "./sections/Dryzun/Cashback.tsx";
import * as $$$$$$33 from "./sections/Dryzun/FaleConosco.tsx";
import * as $$$$$$34 from "./sections/Dryzun/NossasLojas.tsx";
import * as $$$$$$35 from "./sections/Dryzun/ProductShelf.tsx";
import * as $$$$$$36 from "./sections/Footer.tsx";
import * as $$$$$$37 from "./sections/Footer/Footer.tsx";
import * as $$$$$$38 from "./sections/Gallery.tsx";
import * as $$$$$$39 from "./sections/Header/Header.tsx";
import * as $$$$$$40 from "./sections/Images/BannerGrid.tsx";
import * as $$$$$$41 from "./sections/Images/Carousel.tsx";
import * as $$$$$$42 from "./sections/Images/ImageGallery.tsx";
import * as $$$$$$43 from "./sections/Images/ShoppableBanner.tsx";
import * as $$$$$$44 from "./sections/ItWorks.tsx";
import * as $$$$$$93 from "./sections/jaeger/Jaeger.tsx";
import * as $$$$$$45 from "./sections/Links/LinkTree.tsx";
import * as $$$$$$46 from "./sections/Links/Shortcuts.tsx";
import * as $$$$$$47 from "./sections/Miscellaneous/CampaignTimer.tsx";
import * as $$$$$$48 from "./sections/Miscellaneous/CookieConsent.tsx";
import * as $$$$$$49 from "./sections/Miscellaneous/Slide.tsx";
import * as $$$$$$50 from "./sections/Newsletter/Newsletter.tsx";
import * as $$$$$$51 from "./sections/Product/ImageGalleryFrontBack.tsx";
import * as $$$$$$52 from "./sections/Product/NotFound.tsx";
import * as $$$$$$53 from "./sections/Product/NotFoundChallenge.tsx";
import * as $$$$$$54 from "./sections/Product/ProductDetails.tsx";
import * as $$$$$$55 from "./sections/Product/ProductShelf.tsx";
import * as $$$$$$56 from "./sections/Product/ProductShelfTabbed.tsx";
import * as $$$$$$57 from "./sections/Product/SearchResult.tsx";
import * as $$$$$$58 from "./sections/Product/ShelfWithImage.tsx";
import * as $$$$$$59 from "./sections/Product/Wishlist.tsx";
import * as $$$$$$60 from "./sections/Rolex/BackToTopRolex.tsx";
import * as $$$$$$61 from "./sections/Rolex/BreadCrumb.tsx";
import * as $$$$$$62 from "./sections/Rolex/CartTextImage.tsx";
import * as $$$$$$63 from "./sections/Rolex/Contact.tsx";
import * as $$$$$$64 from "./sections/Rolex/Exploring.tsx";
import * as $$$$$$65 from "./sections/Rolex/Exploring2024.tsx";
import * as $$$$$$66 from "./sections/Rolex/ExploringCollection.tsx";
import * as $$$$$$67 from "./sections/Rolex/Gallery.tsx";
import * as $$$$$$68 from "./sections/Rolex/GalleryMini.tsx";
import * as $$$$$$69 from "./sections/Rolex/MenuRolex.tsx";
import * as $$$$$$70 from "./sections/Rolex/PageForm.tsx";
import * as $$$$$$71 from "./sections/Rolex/Quote.tsx";
import * as $$$$$$72 from "./sections/Rolex/Servicing.tsx";
import * as $$$$$$73 from "./sections/Rolex/TagKeyWord.tsx";
import * as $$$$$$74 from "./sections/Rolex/Text.tsx";
import * as $$$$$$75 from "./sections/Rolex/Video.tsx";
import * as $$$$$$76 from "./sections/Rolex/Vitrine.tsx";
import * as $$$$$$77 from "./sections/Rolex/WorldOfRolex.tsx";
import * as $$$$$$78 from "./sections/RolexIndex.tsx";
import * as $$$$$$79 from "./sections/Social/InstagramPosts.tsx";
import * as $$$$$$80 from "./sections/Social/WhatsApp.tsx";
import * as $$$$$$82 from "./sections/Tag-heuer/BannersTagHeue.tsx";
import * as $$$$$$81 from "./sections/Tag-heuer/BannerTagHeuer.tsx";
import * as $$$$$$83 from "./sections/Tag-heuer/ShelfTagHeue.tsx";
import * as $$$$$$84 from "./sections/Tag-heuer/TextTagHeue.tsx";
import * as $$$$$$85 from "./sections/Tag-heuer/VideoTagHeuer.tsx";
import * as $$$$$$86 from "./sections/Theme/Theme.tsx";
import * as $$$$$$87 from "./sections/Tudor/BackToTop.tsx";
import * as $$$$$$88 from "./sections/Tudor/Gallery.tsx";
import * as $$$$$$89 from "./sections/Tudor/ImageAndTextCard.tsx";
import * as $$$$$$90 from "./sections/Tudor/Text.tsx";
import * as $$$$$$91 from "./sections/Tudor/Video.tsx";
import * as $$$$$$92 from "./sections/Tudor/VideoAndTextCard.tsx";

const manifest = {
  "loaders": {
    "site/loaders/availableIcons.ts": $$$2,
    "site/loaders/icons.ts": $$$3,
    "site/loaders/Layouts/ProductCard.tsx": $$$0,
    "site/loaders/List/Sections.tsx": $$$1,
  },
  "sections": {
    "site/sections/Animation/Animation.tsx": $$$$$$0,
    "site/sections/Bvlgari/Bvlgari.tsx": $$$$$$1,
    "site/sections/Cards/IconCardsCarousel.tsx": $$$$$$2,
    "site/sections/Cards/IconCardsCarouselWithImage.tsx": $$$$$$3,
    "site/sections/Cards/ImageCardsCarousel.tsx": $$$$$$4,
    "site/sections/Cards/ImageCardsCarouselWithImage.tsx": $$$$$$5,
    "site/sections/Cartier/Cartier.tsx": $$$$$$6,
    "site/sections/Category/CategoryBanner.tsx": $$$$$$7,
    "site/sections/Category/CategoryGrid.tsx": $$$$$$8,
    "site/sections/Category/CategoryList.tsx": $$$$$$9,
    "site/sections/Category/CategoryText.tsx": $$$$$$10,
    "site/sections/CollectionHub.tsx": $$$$$$11,
    "site/sections/Content/Benefits.tsx": $$$$$$12,
    "site/sections/Content/BlogPosts.tsx": $$$$$$13,
    "site/sections/Content/CallToAction.tsx": $$$$$$14,
    "site/sections/Content/Faq.tsx": $$$$$$15,
    "site/sections/Content/Features.tsx": $$$$$$16,
    "site/sections/Content/Hero.tsx": $$$$$$17,
    "site/sections/Content/ImageSection.tsx": $$$$$$18,
    "site/sections/Content/Intro.tsx": $$$$$$19,
    "site/sections/Content/Logos.tsx": $$$$$$20,
    "site/sections/Content/Partners.tsx": $$$$$$21,
    "site/sections/Content/RichText.tsx": $$$$$$22,
    "site/sections/Content/Table.tsx": $$$$$$23,
    "site/sections/Content/Testimonials.tsx": $$$$$$24,
    "site/sections/Content/TextWithImage.tsx": $$$$$$25,
    "site/sections/CookieDryzun.tsx": $$$$$$26,
    "site/sections/Dryzun/AboutDryzun.tsx": $$$$$$27,
    "site/sections/Dryzun/AboutInstitucional.tsx": $$$$$$28,
    "site/sections/Dryzun/BannerGrid.tsx": $$$$$$29,
    "site/sections/Dryzun/BannerList.tsx": $$$$$$30,
    "site/sections/Dryzun/BannerSingle.tsx": $$$$$$31,
    "site/sections/Dryzun/Cashback.tsx": $$$$$$32,
    "site/sections/Dryzun/FaleConosco.tsx": $$$$$$33,
    "site/sections/Dryzun/NossasLojas.tsx": $$$$$$34,
    "site/sections/Dryzun/ProductShelf.tsx": $$$$$$35,
    "site/sections/Footer.tsx": $$$$$$36,
    "site/sections/Footer/Footer.tsx": $$$$$$37,
    "site/sections/Gallery.tsx": $$$$$$38,
    "site/sections/Header/Header.tsx": $$$$$$39,
    "site/sections/Images/BannerGrid.tsx": $$$$$$40,
    "site/sections/Images/Carousel.tsx": $$$$$$41,
    "site/sections/Images/ImageGallery.tsx": $$$$$$42,
    "site/sections/Images/ShoppableBanner.tsx": $$$$$$43,
    "site/sections/ItWorks.tsx": $$$$$$44,
    "site/sections/jaeger/Jaeger.tsx": $$$$$$93,
    "site/sections/Links/LinkTree.tsx": $$$$$$45,
    "site/sections/Links/Shortcuts.tsx": $$$$$$46,
    "site/sections/Miscellaneous/CampaignTimer.tsx": $$$$$$47,
    "site/sections/Miscellaneous/CookieConsent.tsx": $$$$$$48,
    "site/sections/Miscellaneous/Slide.tsx": $$$$$$49,
    "site/sections/Newsletter/Newsletter.tsx": $$$$$$50,
    "site/sections/Product/ImageGalleryFrontBack.tsx": $$$$$$51,
    "site/sections/Product/NotFound.tsx": $$$$$$52,
    "site/sections/Product/NotFoundChallenge.tsx": $$$$$$53,
    "site/sections/Product/ProductDetails.tsx": $$$$$$54,
    "site/sections/Product/ProductShelf.tsx": $$$$$$55,
    "site/sections/Product/ProductShelfTabbed.tsx": $$$$$$56,
    "site/sections/Product/SearchResult.tsx": $$$$$$57,
    "site/sections/Product/ShelfWithImage.tsx": $$$$$$58,
    "site/sections/Product/Wishlist.tsx": $$$$$$59,
    "site/sections/Rolex/BackToTopRolex.tsx": $$$$$$60,
    "site/sections/Rolex/BreadCrumb.tsx": $$$$$$61,
    "site/sections/Rolex/CartTextImage.tsx": $$$$$$62,
    "site/sections/Rolex/Contact.tsx": $$$$$$63,
    "site/sections/Rolex/Exploring.tsx": $$$$$$64,
    "site/sections/Rolex/Exploring2024.tsx": $$$$$$65,
    "site/sections/Rolex/ExploringCollection.tsx": $$$$$$66,
    "site/sections/Rolex/Gallery.tsx": $$$$$$67,
    "site/sections/Rolex/GalleryMini.tsx": $$$$$$68,
    "site/sections/Rolex/MenuRolex.tsx": $$$$$$69,
    "site/sections/Rolex/PageForm.tsx": $$$$$$70,
    "site/sections/Rolex/Quote.tsx": $$$$$$71,
    "site/sections/Rolex/Servicing.tsx": $$$$$$72,
    "site/sections/Rolex/TagKeyWord.tsx": $$$$$$73,
    "site/sections/Rolex/Text.tsx": $$$$$$74,
    "site/sections/Rolex/Video.tsx": $$$$$$75,
    "site/sections/Rolex/Vitrine.tsx": $$$$$$76,
    "site/sections/Rolex/WorldOfRolex.tsx": $$$$$$77,
    "site/sections/RolexIndex.tsx": $$$$$$78,
    "site/sections/Social/InstagramPosts.tsx": $$$$$$79,
    "site/sections/Social/WhatsApp.tsx": $$$$$$80,
    "site/sections/Tag-heuer/BannersTagHeue.tsx": $$$$$$82,
    "site/sections/Tag-heuer/BannerTagHeuer.tsx": $$$$$$81,
    "site/sections/Tag-heuer/ShelfTagHeue.tsx": $$$$$$83,
    "site/sections/Tag-heuer/TextTagHeue.tsx": $$$$$$84,
    "site/sections/Tag-heuer/VideoTagHeuer.tsx": $$$$$$85,
    "site/sections/Theme/Theme.tsx": $$$$$$86,
    "site/sections/Tudor/BackToTop.tsx": $$$$$$87,
    "site/sections/Tudor/Gallery.tsx": $$$$$$88,
    "site/sections/Tudor/ImageAndTextCard.tsx": $$$$$$89,
    "site/sections/Tudor/Text.tsx": $$$$$$90,
    "site/sections/Tudor/Video.tsx": $$$$$$91,
    "site/sections/Tudor/VideoAndTextCard.tsx": $$$$$$92,
  },
  "apps": {
    "site/apps/deco/ai-assistants.ts": $$$$$$$$$$$0,
    "site/apps/deco/algolia.ts": $$$$$$$$$$$1,
    "site/apps/deco/analytics.ts": $$$$$$$$$$$2,
    "site/apps/deco/brand-assistant.ts": $$$$$$$$$$$3,
    "site/apps/deco/htmx.ts": $$$$$$$$$$$4,
    "site/apps/deco/implementation.ts": $$$$$$$$$$$5,
    "site/apps/deco/vtex.ts": $$$$$$$$$$$6,
    "site/apps/deco/weather.ts": $$$$$$$$$$$7,
    "site/apps/deco/workflows.ts": $$$$$$$$$$$8,
    "site/apps/decohub.ts": $$$$$$$$$$$9,
    "site/apps/site.ts": $$$$$$$$$$$10,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
